### ISSUE TITLE
[FEATURE] - Mogelijkheid om programmatisch validatie aan te roepen

### ISSUE THREAD

**Issue by driesva** [milieuinfo/webcomponent-vl-ui-form#10]
**Wat moet er gebeuren**
Er werd gevraagd om een _search-as-you-type_ te implementeren voor het zoeken op INSZ. Dus van zodra de gebruiker een (correct) INSZ ingeeft, gaan we de gegevens uit MAGDA halen en presenteren aan de gebruiker.

Voor de invoer gebruiken we een vl-input-field. Dat veld beschikt reeds over vl-pattern / vl-form-validation om frontend validatie te doen en de gebruiker te informeren wanneer het INSZ ongeldig is.

In onze huidige implementatie werd dit geïmplementeerd om programmatisch een _submit event_ te sturen (`this._form().dispatchEvent(new Event("submit"));` )

Echter bij Firefox resulteert dit systematisch in een server call, behalve als er aan de form `action="about:blank"` wordt toegevoegd. Vandaar issue #4 . (Echter door https://github.com/milieuinfo/webcomponent-vl-ui-form/pull/6 werkt dit niet meer, zie https://github.com/milieuinfo/webcomponent-vl-ui-form/pull/6#issuecomment-711898597)

Om dit proper af te handelen zou vl-form misschien beter een functie krijgen om validatie programmatisch aan te roepen. Die bijkomend dan een waarde die teruggeeft of de form _valid_ is (zodat we de backend search kunnen lanceren).

Native bestaat hiervoor eigenlijk al _reportValidity_ (zie https://developer.mozilla.org/en-US/docs/Web/API/HTMLFormElement) Maar dit lijkt niet te werken met de huidige vl form validatie.

Ter info, relevante schermen

![image](https://user-images.githubusercontent.com/29454303/97696749-4e91bf80-1aa6-11eb-87a2-bde593144e44.png)
![image](https://user-images.githubusercontent.com/29454303/97696768-5487a080-1aa6-11eb-8346-84d88bdb0630.png)

**Comment by driesva** [comment]
@ZhaodiFengVlaanderen als er nog zaken ontbreken in mijn beschrijving, gelieve een comment toe te voegen

**Comment by ZhaodiFengVlaanderen** [comment]
De form validatie voegt ook visual effect per validatie (groen of rode). 
Dit zal misschien ook tot scope behoren?

**Comment by driesva** [comment]
Dat is voor mij out of scope. In context van de gevraagde functionaliteit maakt het niet uit of er bij validatie een kleur is, een popup, ... Dat is een implementatie(detail) van de validatie zelf. Als dat niet werkt, gelieve daar een ander ticket van te maken.

**Comment by coemans** [comment]
Bij de laatste vl-ui-form (nog niet gepubliceerd maar wel al beschikbaar) kan je o.a. de native `checkValidity` gebruiken.
