### ISSUE TITLE
[BUG] - Default aangemaakt form ontbreekt action attribuut

### ISSUE THREAD

**Issue by ZhaodiFengVlaanderen** [milieuinfo/webcomponent-vl-ui-form#4]
Na verder onderzoeken lijkt mij dat de default aangemaakte form heeft geen attribute `action="about:blank"` .

Hiervoor zorgt onverwacht request in Firefox als wij de form applicative submitted.

**Comment by coemans** [comment]
Lijkt inderdaad valid HTML5 te zijn volgens de standaard, dus zal zo uitgevoerd worden.

> The action and formaction content attributes, if specified, must have a value that is a valid non-empty URL potentially surrounded by spaces.

> If element has no src attribute specified, or its value is the empty string, let url be the URL "about:blank".

**Comment by driesva** [comment]
Ik heb de indruk dat versie 1.0.2 van "vl-ui-form" nu terug het probleem heeft.

**Comment by coemans** [comment]
Kan het probleem verder beschreven worden? Ik zou het probleem namelijk graag reproduceren op de demo pagina van de webcomponent zodat hiervoor regressie testen kunnen toegevoegd worden. Momenteel werkt de demo pagina correct in Firefox, de e2e testen zijn bijgevolg ook groen.

De PR bevat alleen unit testen omdat er reeds e2e testen voorzien waren. Ik vermoed dat de e2e testen uitgebreid kunnen worden in kader van dit probleem.

**Comment by driesva** [comment]
Zie https://github.com/milieuinfo/webcomponent-vl-ui-form/pull/6#issuecomment-711898597
